services:
  adguardhome:
    image: registry.cn-shanghai.aliyuncs.com/sharespace/github-flask-api
    container_name: github-flask-api
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      REPO_OWNER: iCloudBot
      REPO_NAME: DockerRescue
      BRANCH_NAME: main
      GITHUB_TOKEN: ghp_************************
